package mechcraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelGaussRifle extends ModelBase
{
    //fields
    public ModelRenderer coilrailll;
    public ModelRenderer coilraillu;
    public ModelRenderer coilraill;
    public ModelRenderer coilrailr;
    public ModelRenderer coilrailrl;
    public ModelRenderer coilrailru;
    public ModelRenderer coilmagru;
    public ModelRenderer coilmagru1;
    public ModelRenderer coilmagru2;
    public ModelRenderer coilmagru3;
    public ModelRenderer coilmagru4;
    public ModelRenderer coilmagru5;
    public ModelRenderer coilmagru6;
    public ModelRenderer coilmagrl;
    public ModelRenderer coilmagrl1;
    public ModelRenderer coilmagrl2;
    public ModelRenderer coilmagrl3;
    public ModelRenderer coilmagrl4;
    public ModelRenderer coilmagrl5;
    public ModelRenderer coilmagrl6;
    public ModelRenderer coilmagll;
    public ModelRenderer coilmagll1;
    public ModelRenderer coilmagll2;
    public ModelRenderer coilmagll3;
    public ModelRenderer coilmagll4;
    public ModelRenderer coilmagll5;
    public ModelRenderer coilmagll6;
    public ModelRenderer coilmaglu;
    public ModelRenderer coilmaglu1;
    public ModelRenderer coilmaglu2;
    public ModelRenderer coilmaglu3;
    public ModelRenderer coilmaglu4;
    public ModelRenderer coilmaglu5;
    public ModelRenderer coilmaglu6;
    public ModelRenderer barrelr;
    public ModelRenderer barrelu;
    public ModelRenderer barrell;
    public ModelRenderer coilstrutl;
    public ModelRenderer coilstrutr;
    public ModelRenderer coilspacerl;
    public ModelRenderer coilspaceru;
    public ModelRenderer stock1;
    public ModelRenderer stock2l;
    public ModelRenderer stock2r;
    public ModelRenderer stock2;
    public ModelRenderer stock3;
    public ModelRenderer stock4;
    public ModelRenderer stock5;
    public ModelRenderer stock6;
    public ModelRenderer stock7;
    public ModelRenderer stock8;

    public ModelGaussRifle()
    {
        textureWidth = 128;
        textureHeight = 64;

        coilrailll = new ModelRenderer(this, 0, 0);
        coilrailll.addBox(0F, 0F, 0F, 1, 1, 14);
        coilrailll.setRotationPoint(-4F, 2F, 0F);
        coilrailll.setTextureSize(128, 64);
        coilrailll.mirror = true;
        setRotation(coilrailll, 0F, 0F, 0F);
        coilraillu = new ModelRenderer(this, 0, 0);
        coilraillu.addBox(0F, 0F, 0F, 1, 1, 14);
        coilraillu.setRotationPoint(-4F, -2F, 0F);
        coilraillu.setTextureSize(128, 64);
        coilraillu.mirror = true;
        setRotation(coilraillu, 0F, 0F, 0F);
        coilraill = new ModelRenderer(this, 0, 0);
        coilraill.addBox(0F, 0F, 0F, 1, 1, 14);
        coilraill.setRotationPoint(-6F, 0F, 0F);
        coilraill.setTextureSize(128, 64);
        coilraill.mirror = true;
        setRotation(coilraill, 0F, 0F, 0F);
        coilrailr = new ModelRenderer(this, 0, 0);
        coilrailr.addBox(0F, 0F, 0F, 1, 1, 14);
        coilrailr.setRotationPoint(0F, 0F, 0F);
        coilrailr.setTextureSize(128, 64);
        coilrailr.mirror = true;
        setRotation(coilrailr, 0F, 0F, 0F);
        coilrailrl = new ModelRenderer(this, 0, 0);
        coilrailrl.addBox(0F, 0F, 0F, 1, 1, 14);
        coilrailrl.setRotationPoint(-2F, 2F, 0F);
        coilrailrl.setTextureSize(128, 64);
        coilrailrl.mirror = true;
        setRotation(coilrailrl, 0F, 0F, 0F);
        coilrailru = new ModelRenderer(this, 0, 0);
        coilrailru.addBox(0F, 0F, 0F, 1, 1, 14);
        coilrailru.setRotationPoint(-2F, -2F, 0F);
        coilrailru.setTextureSize(128, 64);
        coilrailru.mirror = true;
        setRotation(coilrailru, 0F, 0F, 0F);
        coilmagru = new ModelRenderer(this, 38, 0);
        coilmagru.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru.setRotationPoint(-2F, -1.3F, 0F);
        coilmagru.setTextureSize(128, 64);
        coilmagru.mirror = true;
        setRotation(coilmagru, 0F, 0F, -0.7853982F);
        coilmagru1 = new ModelRenderer(this, 38, 0);
        coilmagru1.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru1.setRotationPoint(-2F, -1.3F, 2F);
        coilmagru1.setTextureSize(128, 64);
        coilmagru1.mirror = true;
        setRotation(coilmagru1, 0F, 0F, -0.7853982F);
        coilmagru2 = new ModelRenderer(this, 38, 0);
        coilmagru2.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru2.setRotationPoint(-2F, -1.3F, 4F);
        coilmagru2.setTextureSize(128, 64);
        coilmagru2.mirror = true;
        setRotation(coilmagru2, 0F, 0F, -0.7853982F);
        coilmagru3 = new ModelRenderer(this, 38, 0);
        coilmagru3.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru3.setRotationPoint(-2F, -1.3F, 6F);
        coilmagru3.setTextureSize(128, 64);
        coilmagru3.mirror = true;
        setRotation(coilmagru3, 0F, 0F, -0.7853982F);
        coilmagru4 = new ModelRenderer(this, 38, 0);
        coilmagru4.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru4.setRotationPoint(-2F, -1.3F, 8F);
        coilmagru4.setTextureSize(128, 64);
        coilmagru4.mirror = true;
        setRotation(coilmagru4, 0F, 0F, -0.7853982F);
        coilmagru5 = new ModelRenderer(this, 38, 0);
        coilmagru5.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru5.setRotationPoint(-2F, -1.3F, 10F);
        coilmagru5.setTextureSize(128, 64);
        coilmagru5.mirror = true;
        setRotation(coilmagru5, 0F, 0F, -0.7853982F);
        coilmagru6 = new ModelRenderer(this, 38, 0);
        coilmagru6.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagru6.setRotationPoint(-2F, -1.3F, 12F);
        coilmagru6.setTextureSize(128, 64);
        coilmagru6.mirror = true;
        setRotation(coilmagru6, 0F, 0F, -0.7853982F);
        coilmagrl = new ModelRenderer(this, 38, 0);
        coilmagrl.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl.setRotationPoint(0F, 0F, 0F);
        coilmagrl.setTextureSize(128, 64);
        coilmagrl.mirror = true;
        setRotation(coilmagrl, 0F, 0F, 0.6981317F);
        coilmagrl1 = new ModelRenderer(this, 38, 0);
        coilmagrl1.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl1.setRotationPoint(0F, 0F, 2F);
        coilmagrl1.setTextureSize(128, 64);
        coilmagrl1.mirror = true;
        setRotation(coilmagrl1, 0F, 0F, 0.6981317F);
        coilmagrl2 = new ModelRenderer(this, 38, 0);
        coilmagrl2.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl2.setRotationPoint(0F, 0F, 4F);
        coilmagrl2.setTextureSize(128, 64);
        coilmagrl2.mirror = true;
        setRotation(coilmagrl2, 0F, 0F, 0.6981317F);
        coilmagrl3 = new ModelRenderer(this, 38, 0);
        coilmagrl3.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl3.setRotationPoint(0F, 0F, 6F);
        coilmagrl3.setTextureSize(128, 64);
        coilmagrl3.mirror = true;
        setRotation(coilmagrl3, 0F, 0F, 0.6981317F);
        coilmagrl4 = new ModelRenderer(this, 38, 0);
        coilmagrl4.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl4.setRotationPoint(0F, 0F, 8F);
        coilmagrl4.setTextureSize(128, 64);
        coilmagrl4.mirror = true;
        setRotation(coilmagrl4, 0F, 0F, 0.6981317F);
        coilmagrl5 = new ModelRenderer(this, 38, 0);
        coilmagrl5.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl5.setRotationPoint(0F, 0F, 10F);
        coilmagrl5.setTextureSize(128, 64);
        coilmagrl5.mirror = true;
        setRotation(coilmagrl5, 0F, 0F, 0.6981317F);
        coilmagrl6 = new ModelRenderer(this, 38, 0);
        coilmagrl6.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagrl6.setRotationPoint(0F, 0F, 12F);
        coilmagrl6.setTextureSize(128, 64);
        coilmagrl6.mirror = true;
        setRotation(coilmagrl6, 0F, 0F, 0.6981317F);
        coilmagll = new ModelRenderer(this, 38, 0);
        coilmagll.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll.setRotationPoint(-6F, 0.7F, 0F);
        coilmagll.setTextureSize(128, 64);
        coilmagll.mirror = true;
        setRotation(coilmagll, 0F, 0F, -0.7679449F);
        coilmagll1 = new ModelRenderer(this, 38, 0);
        coilmagll1.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll1.setRotationPoint(-6F, 0.7F, 2F);
        coilmagll1.setTextureSize(128, 64);
        coilmagll1.mirror = true;
        setRotation(coilmagll1, 0F, 0F, -0.7679449F);
        coilmagll2 = new ModelRenderer(this, 38, 0);
        coilmagll2.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll2.setRotationPoint(-6F, 0.7F, 4F);
        coilmagll2.setTextureSize(128, 64);
        coilmagll2.mirror = true;
        setRotation(coilmagll2, 0F, 0F, -0.7679449F);
        coilmagll3 = new ModelRenderer(this, 38, 0);
        coilmagll3.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll3.setRotationPoint(-6F, 0.7F, 6F);
        coilmagll3.setTextureSize(128, 64);
        coilmagll3.mirror = true;
        setRotation(coilmagll3, 0F, 0F, -0.7679449F);
        coilmagll4 = new ModelRenderer(this, 38, 0);
        coilmagll4.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll4.setRotationPoint(-6F, 0.7F, 8F);
        coilmagll4.setTextureSize(128, 64);
        coilmagll4.mirror = true;
        setRotation(coilmagll4, 0F, 0F, -0.7679449F);
        coilmagll5 = new ModelRenderer(this, 38, 0);
        coilmagll5.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll5.setRotationPoint(-6F, 0.7F, 10F);
        coilmagll5.setTextureSize(128, 64);
        coilmagll5.mirror = true;
        setRotation(coilmagll5, 0F, 0F, -0.7679449F);
        coilmagll6 = new ModelRenderer(this, 38, 0);
        coilmagll6.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmagll6.setRotationPoint(-6F, 0.7F, 12F);
        coilmagll6.setTextureSize(128, 64);
        coilmagll6.mirror = true;
        setRotation(coilmagll6, 0F, 0F, -0.7679449F);
        coilmaglu = new ModelRenderer(this, 38, 0);
        coilmaglu.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu.setRotationPoint(-4F, -2F, 0F);
        coilmaglu.setTextureSize(128, 64);
        coilmaglu.mirror = true;
        setRotation(coilmaglu, 0F, 0F, 0.6806784F);
        coilmaglu1 = new ModelRenderer(this, 38, 0);
        coilmaglu1.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu1.setRotationPoint(-4F, -2F, 2F);
        coilmaglu1.setTextureSize(128, 64);
        coilmaglu1.mirror = true;
        setRotation(coilmaglu1, 0F, 0F, 0.6806784F);
        coilmaglu2 = new ModelRenderer(this, 38, 0);
        coilmaglu2.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu2.setRotationPoint(-4F, -2F, 4F);
        coilmaglu2.setTextureSize(128, 64);
        coilmaglu2.mirror = true;
        setRotation(coilmaglu2, 0F, 0F, 0.6806784F);
        coilmaglu3 = new ModelRenderer(this, 38, 0);
        coilmaglu3.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu3.setRotationPoint(-4F, -2F, 6F);
        coilmaglu3.setTextureSize(128, 64);
        coilmaglu3.mirror = true;
        setRotation(coilmaglu3, 0F, 0F, 0.6806784F);
        coilmaglu4 = new ModelRenderer(this, 38, 0);
        coilmaglu4.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu4.setRotationPoint(-4F, -2F, 8F);
        coilmaglu4.setTextureSize(128, 64);
        coilmaglu4.mirror = true;
        setRotation(coilmaglu4, 0F, 0F, 0.6806784F);
        coilmaglu5 = new ModelRenderer(this, 38, 0);
        coilmaglu5.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu5.setRotationPoint(-4F, -2F, 10F);
        coilmaglu5.setTextureSize(128, 64);
        coilmaglu5.mirror = true;
        setRotation(coilmaglu5, 0F, 0F, 0.6806784F);
        coilmaglu6 = new ModelRenderer(this, 38, 0);
        coilmaglu6.addBox(0F, 0F, 0F, 1, 3, 1);
        coilmaglu6.setRotationPoint(-4F, -2F, 12F);
        coilmaglu6.setTextureSize(128, 64);
        coilmaglu6.mirror = true;
        setRotation(coilmaglu6, 0F, 0F, 0.6806784F);
        barrelr = new ModelRenderer(this, 30, 3);
        barrelr.addBox(0F, 0F, 0F, 1, 5, 3);
        barrelr.setRotationPoint(-2F, -2F, 14F);
        barrelr.setTextureSize(128, 64);
        barrelr.mirror = true;
        setRotation(barrelr, 0F, 0F, 0F);
        barrelu = new ModelRenderer(this, 17, 47);
        barrelu.addBox(0F, 0F, 0F, 1, 1, 3);
        barrelu.setRotationPoint(-3F, -1F, 14F);
        barrelu.setTextureSize(128, 64);
        barrelu.mirror = true;
        setRotation(barrelu, 0F, 0F, 0F);
        barrell = new ModelRenderer(this, 30, 3);
        barrell.addBox(0F, 0F, 0F, 1, 5, 3);
        barrell.setRotationPoint(-4F, -2F, 14F);
        barrell.setTextureSize(128, 64);
        barrell.mirror = true;
        setRotation(barrell, 0F, 0F, 0F);
        coilstrutl = new ModelRenderer(this, 42, 0);
        coilstrutl.addBox(0F, 0F, 0F, 3, 1, 1);
        coilstrutl.setRotationPoint(-6F, 0F, 14F);
        coilstrutl.setTextureSize(128, 64);
        coilstrutl.mirror = true;
        setRotation(coilstrutl, 0F, 0F, 0F);
        coilstrutr = new ModelRenderer(this, 42, 0);
        coilstrutr.addBox(0F, 0F, 0F, 3, 1, 1);
        coilstrutr.setRotationPoint(-2F, 0F, 14F);
        coilstrutr.setTextureSize(128, 64);
        coilstrutr.mirror = true;
        setRotation(coilstrutr, 0F, 0F, 0F);
        coilspacerl = new ModelRenderer(this, 0, 0);
        coilspacerl.addBox(0F, 0F, 0F, 1, 1, 1);
        coilspacerl.setRotationPoint(-3F, 2F, 0F);
        coilspacerl.setTextureSize(128, 64);
        coilspacerl.mirror = true;
        setRotation(coilspacerl, 0F, 0F, 0F);
        coilspaceru = new ModelRenderer(this, 0, 0);
        coilspaceru.addBox(0F, 0F, 0F, 1, 1, 1);
        coilspaceru.setRotationPoint(-3F, -2F, 0F);
        coilspaceru.setTextureSize(128, 64);
        coilspaceru.mirror = true;
        setRotation(coilspaceru, 0F, 0F, 0F);
        stock1 = new ModelRenderer(this, 16, 52);
        stock1.addBox(0F, 0F, 0F, 1, 2, 10);
        stock1.setRotationPoint(-3F, 1F, 14F);
        stock1.setTextureSize(128, 64);
        stock1.mirror = true;
        setRotation(stock1, 0F, 0F, 0F);
        stock2l = new ModelRenderer(this, 0, 17);
        stock2l.addBox(0F, 0F, 0F, 1, 2, 6);
        stock2l.setRotationPoint(-4F, 0F, 17F);
        stock2l.setTextureSize(128, 64);
        stock2l.mirror = true;
        setRotation(stock2l, 0F, 0F, 0F);
        stock2r = new ModelRenderer(this, 0, 17);
        stock2r.addBox(0F, 0F, 0F, 1, 2, 6);
        stock2r.setRotationPoint(-2F, 0F, 17F);
        stock2r.setTextureSize(128, 64);
        stock2r.mirror = true;
        setRotation(stock2r, 0F, 0F, 0F);
        stock2 = new ModelRenderer(this, 30, 0);
        stock2.addBox(0F, 0F, 0F, 1, 1, 2);
        stock2.setRotationPoint(-3F, -1F, 17F);
        stock2.setTextureSize(128, 64);
        stock2.mirror = true;
        setRotation(stock2, 0F, 0F, 0F);
        stock3 = new ModelRenderer(this, 0, 33);
        stock3.addBox(0F, 0F, 0F, 3, 2, 8);
        stock3.setRotationPoint(-4F, 0F, 23F);
        stock3.setTextureSize(128, 64);
        stock3.mirror = true;
        setRotation(stock3, 0F, 0F, 0F);
        stock4 = new ModelRenderer(this, 0, 43);
        stock4.addBox(0F, 0F, 0F, 3, 2, 10);
        stock4.setRotationPoint(-4F, 2F, 24F);
        stock4.setTextureSize(128, 64);
        stock4.mirror = true;
        setRotation(stock4, 0F, 0F, 0F);
        stock5 = new ModelRenderer(this, 0, 55);
        stock5.addBox(0F, 0F, 0F, 3, 4, 5);
        stock5.setRotationPoint(-4F, 0F, 33.93333F);
        stock5.setTextureSize(128, 64);
        stock5.mirror = true;
        setRotation(stock5, 0F, 0F, 0F);
        stock6 = new ModelRenderer(this, 0, 25);
        stock6.addBox(0F, 0F, 0F, 3, 2, 6);
        stock6.setRotationPoint(-4F, 4F, 33F);
        stock6.setTextureSize(128, 64);
        stock6.mirror = true;
        setRotation(stock6, 0F, 0F, 0F);
        stock7 = new ModelRenderer(this, 15, 36);
        stock7.addBox(0F, 0F, 0F, 3, 1, 3);
        stock7.setRotationPoint(-4F, 1F, 31F);
        stock7.setTextureSize(128, 64);
        stock7.mirror = true;
        setRotation(stock7, 0F, 0F, 0F);
        stock8 = new ModelRenderer(this, 38, 58);
        stock8.addBox(0F, 0F, 0F, 3, 1, 5);
        stock8.setRotationPoint(-4F, 4F, 28F);
        stock8.setTextureSize(128, 64);
        stock8.mirror = true;
        setRotation(stock8, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        coilrailll.render(f5);
        coilraillu.render(f5);
        coilraill.render(f5);
        coilrailr.render(f5);
        coilrailrl.render(f5);
        coilrailru.render(f5);
        coilmagru.render(f5);
        coilmagru1.render(f5);
        coilmagru2.render(f5);
        coilmagru3.render(f5);
        coilmagru4.render(f5);
        coilmagru5.render(f5);
        coilmagru6.render(f5);
        coilmagrl.render(f5);
        coilmagrl1.render(f5);
        coilmagrl2.render(f5);
        coilmagrl3.render(f5);
        coilmagrl4.render(f5);
        coilmagrl5.render(f5);
        coilmagrl6.render(f5);
        coilmagll.render(f5);
        coilmagll1.render(f5);
        coilmagll2.render(f5);
        coilmagll3.render(f5);
        coilmagll4.render(f5);
        coilmagll5.render(f5);
        coilmagll6.render(f5);
        coilmaglu.render(f5);
        coilmaglu1.render(f5);
        coilmaglu2.render(f5);
        coilmaglu3.render(f5);
        coilmaglu4.render(f5);
        coilmaglu5.render(f5);
        coilmaglu6.render(f5);
        barrelr.render(f5);
        barrelu.render(f5);
        barrell.render(f5);
        coilstrutl.render(f5);
        coilstrutr.render(f5);
        coilspacerl.render(f5);
        coilspaceru.render(f5);
        stock1.render(f5);
        stock2l.render(f5);
        stock2r.render(f5);
        stock2.render(f5);
        stock3.render(f5);
        stock4.render(f5);
        stock5.render(f5);
        stock6.render(f5);
        stock7.render(f5);
        stock8.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
